apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: broker-0
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: broker-1
      port: 9094
      targetPort: 9094
      protocol: TCP
    - name: broker-2
      port: 9096
      targetPort: 9096
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-external
  namespace: default
subsets:
  # Broker 0
  - addresses:
      - ip: 172.19.0.20
    ports:
      - name: broker-0
        port: 9092
  # Broker 1
  - addresses:
      - ip: 172.19.0.21
    ports:
      - name: broker-1
        port: 9094
  # Broker 2
  - addresses:
      - ip: 172.19.0.22
    ports:
      - name: broker-2
        port: 9096
---
# Schema Registry (변동 없음)
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-external
  namespace: default
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: schema-registry-external
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.23
    ports:
      - name: http
        port: 8081
