apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - rollout.yaml
  - service.yaml
  - virtual-service.yaml
  - hpa.yaml
  - pdb.yaml
  - configmap.yaml

commonLabels:
  app: demo-backend
  managed-by: kustomize
