apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  namespace: default
  labels:
    app: demo-backend
  annotations:
    ignore-check.kube-linter.io/dangling-service: "Verified rollout matches"
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: demo-backend
  type: ClusterIP
