apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - namespace.yaml
  - policies.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.6.2 # 2025-11-10 기준 LTS 가정
    releaseName: kyverno
    namespace: kyverno
    valuesFile: values.yaml
