apiVersion: v1
kind: Service
metadata:
  name: opensearch-external
  namespace: default
  annotations:
    ignore-check.kube-linter.io/dangling-service: "External service"
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opensearch-external
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.45
    ports:
      - name: http
        port: 9200
