apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - service.yaml
  - virtual-service.yaml
  - hpa.yaml
  - pdb.yaml
  # - sealed-secrets.yaml # Uncomment after encrypting secrets
