blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Questions & Discussions
    url: https://github.com/buenhyden/hy-home.k8s/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ê°€ ìˆìœ¼ì‹ ê°€ìš”? Discussionì—ì„œ ë¨¼ì € ë…¼ì˜í•´ ë³´ì„¸ìš”.
  - name: ğŸ“– Documentation
    url: https://github.com/buenhyden/hy-home.k8s/tree/main/docs
    about: ë¬¸ì œ í•´ê²° ì „ì— ë¬¸ì„œë¥¼ ë¨¼ì € í™•ì¸í•´ ë³´ì„¸ìš”.
