apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.5.1 # 2025-11-10 기준 최신 버전 가정
    releaseName: alloy
    namespace: observability
    valuesFile: values.yaml
