apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.16.0 # 2025-11-10 기준 LTS 가정
    releaseName: sealed-secrets
    namespace: sealed-secrets
    valuesFile: values.yaml
    additionalOptions:
      createNamespace: true
