apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - postgres/service.yaml
  - postgres/service-entry.yaml
  - redis/service.yaml
  - redis/service-entry.yaml
  - kafka/service.yaml
  - kafka/service-entry.yaml
  # - opensearch/service.yaml
  # - opensearch/service-entry.yaml
  - egress-policy.yaml # 아래 정책 파일 추가
