apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - namespace.yaml
  - pool-config.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.8 # 2025-11-10 기준 최신 안정 버전 가정
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
