apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
  - namespace.yaml
  # - sealed-secrets.yaml # (암호화 후 주석 해제하여 포함)

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.15.0 # 2025-11-10 기준 최신 차트 가정
    releaseName: airflow
    namespace: airflow
    valuesFile: values.yaml
